// Bakes the vendored woff2 files into TS modules so the EPUB builder can embed
// them identically in Node (tests, CLI) and in the browser, with no fetch at
// runtime. Run: npm run embed:font
import { readFile, writeFile } from 'node:fs/promises';

const FONTS = [
  {
    woff2: 'FrankRuhlLibre-hebrew.woff2',
    license: 'OFL.txt',
    module: 'frankRuhl.ts',
    constant: 'FRANK_RUHL',
    fn: 'frankRuhlBytes',
    note: 'Frank Ruhl Libre, Hebrew subset, variable weight 400-700.',
    terms: 'SIL Open Font License 1.1 — embedding is expressly permitted.',
  },
  {
    woff2: 'TaameyD-hebrew.woff2',
    license: 'LICENSE-TaameyD.txt',
    module: 'taameyD.ts',
    constant: 'TAAMEY_D',
    fn: 'taameyDBytes',
    note:
      "Taamey D, Hebrew subset. Carries all thirty-one te'amim and positions " +
      "them with Denckla's logic, so a letter taking two marks below sets them " +
      'side by side rather than on top of each other.',
    terms:
      'GNU GPL v2 with the font embedding exception, which states that ' +
      'embedding it in a document does not place the document under the GPL.',
  },
];

for (const f of FONTS) {
  const font = await readFile(`src/assets/fonts/${f.woff2}`);
  const license = await readFile(`src/assets/fonts/${f.license}`, 'utf8');

  await writeFile(
    `src/assets/fonts/${f.module}`,
    `// GENERATED by scripts/embed-font.mjs — do not edit by hand.
// ${f.note}
// ${f.terms}
export const ${f.constant}_WOFF2_BASE64 =
  '${font.toString('base64')}';

export const ${f.constant}_LICENSE = ${JSON.stringify(license)};

/** Decode to bytes for zipping into an EPUB. */
export function ${f.fn}(): Uint8Array {
  const bin = atob(${f.constant}_WOFF2_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
`,
  );
  console.log(`${f.module}: embedded ${font.length} bytes of woff2`);
}
